# Generated by Django 5.0.2 on 2024-05-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgroProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer_name', models.CharField(max_length=200, null=True)),
                ('Product_name', models.CharField(max_length=10)),
                ('Product_description', models.TextField(blank=True, null=True)),
                ('Price', models.IntegerField(default=0)),
            ],
        ),
    ]
