# Generated by Django 5.0.2 on 2024-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0002_agroproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='agroproduct',
            name='email',
            field=models.EmailField(max_length=254, null=True, unique=True),
        ),
    ]
