# Generated by Django 5.0.2 on 2024-05-15 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmerapp', '0004_triggerrecord'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TriggerRecord',
        ),
    ]
